### ISSUE TITLE
Error popup after adding the block on front page

### ISSUE THREAD

**Issue by mudrd8mz** [SergioComeron/moodle-block-common_courses#1]
![image](https://user-images.githubusercontent.com/85831/48257537-0e495a80-e413-11e8-9059-5983c71c8408.png)

**Comment by SergioComeron** [comment]
I have not succeeded in reproducing the error. Did it come out when you added it to the site-home?.
Anyway, this will change when I solve #2

**Comment by mudrd8mz** [comment]
I am sorry, this must be some local issue unrelated to your plugin. I am getting it even without it installed.
