### ISSUE TITLE
Better way to find common courses 

### ISSUE THREAD

**Issue by mudrd8mz** [SergioComeron/moodle-block-common_courses#3]
The current implementation calls `enrol_get_all_users_courses()` twice for each user and then find the intersection.

The is already an existing Moodle core API function for finding such courses - please see `enrol_get_shared_courses()`

**Comment by SergioComeron** [comment]
Hi David, 
It's true, I did not know that function. I change it for the next version.
Thanks!

**Comment by SergioComeron** [comment]
Solved on new version
