### ISSUE TITLE
Suggested short description

### ISSUE THREAD

**Issue by wildgirl** [SergioComeron/moodle-block-common_courses#5]
Hello Sergio,

How about the following as a short description for your Common Courses block:

_This block lists any courses you have in common (i.e. you are both enrolled in) with the user whose profile you are viewing._

**Comment by SergioComeron** [comment]
Hi Wildgirl, 
I think it's perfect for the short description. I  will change this in the new version with the other issues solutions. 

Thanks!

**Comment by SergioComeron** [comment]
Solved on new version
